# Generated by Django 3.1.1 on 2020-10-04 19:54

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_auto_20201004_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя автора')),
                ('content', models.TextField(verbose_name='Текст комментария')),
                ('photo', models.ImageField(blank=True, upload_to='avatar/%Y/%m/%d', verbose_name='Аватар')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата добавления(обнавления) комментария')),
                ('likes', models.IntegerField(verbose_name='Понравилось')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='commentaries.commentmodel')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.posts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
