# Generated by Django 3.1.1 on 2020-10-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Понравилось'),
        ),
    ]
